server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/case_db
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
